# 실습1
- load_data()
- LogisticRegression()
- logistic_model.fit(train_X, train_y)
- logistic_model.predict(test_X)

In [ ]:
from data_plot import *   

import warnings
warnings.filterwarnings(action='ignore')

import numpy as np
from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import train_test_split

# 데이터를 생성하고 반환하는 함수입니다.
def load_data():
    
    np.random.seed(0)
    
    X = np.random.normal(size = 100)
    y = (X > 0).astype(np.float)
    X[X > 0] *= 5
    X += .7 * np.random.normal(size = 100)
    X = X[:, np.newaxis]
    
    train_X, test_X, train_y, test_y = train_test_split(X, y, test_size = 0.2, random_state = 100)
    
    return train_X, test_X, train_y, test_y
"""
1. 로지스틱 회귀 모델을 구현하고, 
   학습 결과를 확인할 수 있는 main() 함수를 완성합니다. 
   
   Step01. 데이터를 불러옵니다.
   
   Step02. 로지스틱 회귀 모델을 정의합니다.
   
   Step03. 학습용 데이터로 로지스틱 회귀 모델을
           학습시킵니다.
   
   Step04. 테스트용 데이터로 예측한 분류 결과를
           확인합니다.
"""
def main():
    
    train_X, test_X, train_y, test_y = None
    
    logistic_model = None
    
    None
    
    predicted = None
    
    # 예측 결과 확인하기 
    print("예측 결과 :", predicted[:10])
    
    plot_logistic_regression(logistic_model, train_X, train_y)
    
    return logistic_model

if __name__ == "__main__":
    main()


# 실습2
- pd.read_csv('dataset.csv')
- data.drop('Class', axis=1)
- data['Class']
- SVC()
- svm.fit(train_X, train_y)
- svm.predict(test_X)

In [ ]:
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  

import warnings
warnings.filterwarnings(action='ignore')

from sklearn.model_selection import train_test_split  
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix 
"""
1. data 폴더 내에 있는 dataset.csv파일을 불러오고, 
   학습용 데이터와 테스트용 데이터를 분리하여 
   반환하는 함수를 구현합니다.
   
   Step01. pandas의 read_csv() 함수를 이용하여 
           data 폴더 내에 있는 dataset.csv파일을
           불러옵니다. 
   
   Step02. 데이터 X와 y를 분리합니다.
           데이터 폴더에 있는 dataset.csv 파일을
           확인하고,
           
           X 데이터에는 'Class' 컬럼을 제외한 나머지 컬럼들을,
           y 데이터에는 'Class' 컬럼을 분리하여 저장합니다.
"""
def load_data():
    
    data = None
    
    X = None
    y = None
    
    train_X, test_X, train_y, test_y = train_test_split(X, y, test_size = 0.2, random_state = 0)
    print(X, y)
    return train_X, test_X, train_y, test_y
    
"""
2. SVM 모델을 불러오고,
   학습용 데이터에 맞추어 학습시킨 후, 
   테스트 데이터에 대한 예측 결과를 반환하는 함수를
   구현합니다.
   
   Step01. SVM 모델을 정의합니다.
   
   Step02. SVM 모델을 학습용 데이터에 맞추어
           학습시킵니다.
   
   Step03. 학습된 모델을 이용하여 
           테스트 데이터에 대한 예측을 수행합니다. 
"""
def SVM(train_X, test_X, train_y, test_y):
    
    svm = None
    
    None
    
    pred_y = None
    
    return pred_y
    
# 데이터를 불러오고, 모델 예측 결과를 확인하는 main 함수입니다.
def main():
    
    train_X, test_X, train_y, test_y = load_data()
    
    pred_y = SVM(train_X, test_X, train_y, test_y)
    
    # SVM 분류 결과값을 출력합니다.
    print("\nConfusion matrix : \n",confusion_matrix(test_y,pred_y))  
    print("\nReport : \n",classification_report(test_y,pred_y)) 

if __name__ == "__main__":
    main()


# 실습3 
- 8/20
- 5/8
- 12/20
- 2/12
- p_confirm_spam * p_spam / (7/20)
- p_confirm_ham * p_ham / (7/20)

In [1]:
import numpy as np

"""
1. "확인" 이라는 키워드가 등장했을 때 
    해당 메일이 스팸 메일인지 정상 메일인지
    판별하기 위한 함수를 구현합니다.
"""
def bayes_theorem():
    # 1. P(“스팸 메일”) 의 확률을 구하세요.
    p_spam = 8/20
    
    # 2. P(“확인” | “스팸 메일”) 의 확률을 구하세요.
    p_confirm_spam = 5/8
    
    # 3. P(“정상 메일”) 의 확률을 구하세요.
    p_ham = 12/20
    
    # 4. P(“확인” | "정상 메일" ) 의 확률을 구하세요.
    p_confirm_ham = 2/12
    
    # 5. P( "스팸 메일" | "확인" ) 의 확률을 구하세요.
    p_spam_confirm = p_confirm_spam * p_spam / (7/20)
    
    # 6. P( "정상 메일" | "확인" ) 의 확률을 구하세요.
    p_ham_confirm = p_confirm_ham * p_ham / (7/20)
    
    return p_spam_confirm, p_ham_confirm

def main():
    
    p_spam_confirm, p_ham_confirm = bayes_theorem()
    
    print("P(spam|confirm) = ",p_spam_confirm, "\nP(ham|confirm) = ",p_ham_confirm, "\n")
        
    # 두 값을 비교하여 확인 키워드가 스팸에 가까운지 정상 메일에 가까운지 확인합니다.
    value = [p_spam_confirm, p_ham_confirm]
    
    if p_spam_confirm > p_ham_confirm:
        print( round(value[0] * 100, 2), "% 의 확률로 스팸 메일에 가깝습니다.")
    else :
        print( round(value[1] * 100, 2), "% 의 확률로 일반 메일에 가깝습니다.")


if __name__ == "__main__":
    main()


P(spam|confirm) =  0.7142857142857143 
P(ham|confirm) =  0.2857142857142857 

71.43 % 의 확률로 스팸 메일에 가깝습니다.


# 실습 4
- train_test_split(X, y, train_size=0.8, test_size=0.2, random_state=0)
- GaussianNB()
- model.fit(train_X, train_y)
- model.predict(test_X)

In [ ]:
from sklearn.datasets import load_wine

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

"""
1. 데이터를 불러오고, 
   불러온 데이터를 학습용, 테스트용 데이터로 
   분리하여 반환하는 함수를 구현합니다.
   
   Step01. 사이킷런에 저장되어 있는 데이터를 
           (X, y) 형태로 불러옵니다.
   
   Step02. 불러온 데이터를 
           학습용 데이터와 테스트용 데이터로 분리합니다.
           
           학습용 데이터 : 80%, 테스트용 데이터 : 20%, 
           
           일관된 결과 확인을 위해 random_state를 
           0 으로 설정합니다.
"""
def load_data():
    
    X, y = load_wine(return_X_y = True)
    
    print("데이터 확인해보기 :\n", X[:1])
    
    train_X, test_X, train_y, test_y = None
    
    return train_X, test_X, train_y, test_y
    
"""
2. 가우시안 나이브 베이즈 모델을 불러오고,
   학습을 진행한 후 테스트 데이터에 대한 
   예측값을 반환하는 함수를 구현합니다.
   
   Step01. 가우시안 나이브 베이즈 모델을 정의합니다.
   
   Step02. 학습용 데이터에 대해 모델을 학습시킵니다.
   
   Step03. 테스트 데이터에 대한 모델 예측을 수행합니다.
"""
def Gaussian_NB(train_X, test_X, train_y, test_y):
    
    model = None
    
    None
    
    predicted = None
    
    return predicted
    
# 데이터 불러오기, 모델 예측 결과를 확인할 수 있는 함수입니다.
def main():
    
    train_X, test_X, train_y, test_y = load_data()
    
    predicted = Gaussian_NB(train_X, test_X, train_y, test_y)
    
    ## 모델 정확도를 통해 분류 성능을 확인해봅니다.
    print("\nModel Accuracy : ")
    print(accuracy_score(test_y, predicted))

if __name__ == "__main__":
    main()


# 실습 5
- load_data()
- confusion_matrix(test_y, y_pred)
- cm, test_y, y_pred, classes=class_names
- cm, test_y, y_pred, classes=class_names, normalize = True

In [ ]:
from elice_utils import EliceUtils
elice_utils = EliceUtils()

import warnings
warnings.filterwarnings(action='ignore')

import numpy as np
import matplotlib.pyplot as plt

from sklearn.svm import SVC
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.utils.multiclass import unique_labels

# 데이터를 불러와 학습용, 테스트용 데이터로 분리하여 반환하는 함수입니다.
def load_data():
    
    X, y = load_wine(return_X_y = True)
    class_names = load_wine().target_names
    
    train_X, test_X, train_y, test_y = train_test_split(X, y, test_size =0.3, random_state=0)
    
    return train_X, test_X, train_y, test_y, class_names

# Confusion matrix 시각화를 위한 함수입니다.
def plot_confusion_matrix(cm, y_true, y_pred, classes, normalize=False, cmap=plt.cm.OrRd):
                          
    title = ""
    if normalize:
        title = 'Normalized confusion matrix'
    else:
        title = 'Confusion matrix'
    
    classes = classes[unique_labels(y_true, y_pred)]
    if normalize:
        # 정규화 할 때는 모든 값을 더해서 합이 1이 되도록 각 데이터를 스케일링 합니다.
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]

    print(title, ":\n", cm)

    fig, ax = plt.subplots()
    im = ax.imshow(cm, interpolation='nearest', cmap=cmap)
    ax.figure.colorbar(im, ax=ax)
    ax.set(xticks=np.arange(cm.shape[1]),
           yticks=np.arange(cm.shape[0]),
           xticklabels=classes, yticklabels=classes,
           title=title,
           ylabel='True label',
           xlabel='Predicted label')

    # label을 45도 회전해서 보여주도록 변경
    plt.setp(ax.get_xticklabels(), rotation=45, ha="right",
             rotation_mode="anchor")

    # confusion matrix 실제 값 뿌리기
    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            ax.text(j, i, format(cm[i, j], fmt),
                    ha="center", va="center",
                    color="white" if cm[i, j] > thresh else "black")
    fig.tight_layout()
    
    plt.savefig('confusion matrix.png')
    elice_utils.send_image('confusion matrix.png')

"""
1. 혼동 행렬을 계산하고, 
   시각화하기 위한 main() 함수를 완성합니다.
   
   Step01. 데이터를 불러옵니다.
   
   Step02. 분류 예측 결과를 평가하기 위한 혼동 행렬을 계산합니다.
   
   Step03. confusion matrix를 시각화하여 출력합니다.
           plot_confusion_matrix 함수의 인자를 참고하여 
           None을 채워보세요.
           
           3-1. 혼동 행렬 시각화 결과를 확인합니다. test_y와 y_pred를 비교합니다.
           3-2. 함수의 인자 normalize값을 True로 설정하여 
                정규화된 혼동 행렬 시각화 결과를 확인합니다.
           
"""
def main():
    
    train_X, test_X, train_y, test_y, class_names = None
    
    # SVM 모델로 분류기를 생성하고 학습합니다.
    classifier = SVC()
    y_pred = classifier.fit(train_X, train_y).predict(test_X)
    
    cm = None
    
    plot_confusion_matrix(None, None, None, classes=None)
    
    # 정규화 된 혼동 행렬을 시각화합니다.
    plot_confusion_matrix(None, None, None, classes=None, normalize = None)
    
    return cm
    
if __name__ == "__main__":
    main()


# 실습6
- 아래 코드를 실행하면 표가 나온다. 표를 보고 값을 넣어주면 된다.
- 7/10
- 2/4
- 2/3


In [ ]:
import pandas as pd

def main():
    # 실제 값
    y_true = pd.Series(
        ["not mafia", "not mafia", "mafia", "not mafia", "mafia", 
        "not mafia", "not mafia", "mafia", "not mafia", "not mafia"]
        )
    # 예측된 값
    y_pred = pd.Series(
        ["mafia", "mafia", "not mafia", "not mafia", "mafia", 
        "not mafia", "not mafia", "mafia", "not mafia", "not mafia"]
        )
    
    print("1. 혼동 행렬 :\n",pd.crosstab(y_true, y_pred, rownames=['실제'], colnames=['예측'], margins=True))
    
    
    """
    1. 실행 버튼을 클릭하여 
       마피아(mafia)와 시민(not mafia)으로 분류된 혼동 행렬을 확인합니다.
    """
    
    """
    2. 실행 결과값을 토대로 
       마피아를 제대로 분석했는 지에 대한 
       accuracy, precision, recall을 구합니다.
    """
    accuracy = None
    
    precision = None
    
    recall = None
    
    print("\naccuracy : ", accuracy)
    print("precision : ", precision)
    print("recall : ", recall)
    
    return accuracy, precision, recall
    
if __name__ == "__main__":
    main()

# 실습7

In [3]:
from sklearn.model_selection import train_test_split
#from draw_image import draw_digit_images
from sklearn.datasets import load_digits

from sklearn.svm import SVC

from sklearn.metrics import confusion_matrix
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import accuracy_score

import warnings
warnings.filterwarnings(action = 'ignore')

"""
    1. digits 데이터를 불러오고,
       학습을 위한 전처리를 진행하는 
       load_data() 함수를 구현합니다.
       
       Step01. digits 데이터를 불러옵니다.
       
       Step02. 데이터를 학습용 데이터와 
               테스트용 데이터로 분리합니다.
               (train:80%, test:20%, random_state:100)
"""
def load_data():
    X, y = load_digits(return_X_y=True)
    
    train_X, test_X, train_y, test_y = train_test_split(X, y, train_size=0.8, test_size=0.2, random_state=100)
    
    return train_X, test_X, train_y, test_y
    
    
"""
    2. SVM 분류기를 활용하여 
       테스트 데이터에 대한 예측값을 반환하는 
       SVM_clf() 함수를 구현합니다.
"""
def SVM_clf(train_X, test_X, train_y):
    model = SVC()
    model.fit(train_X, train_y)
    pred = model.predict(test_X)
    
    return pred


"""
    3. 출력된 Confusion Matrix 를 통해 
       인덱스 3의 precision과 recall, 
       그리고 전체 데이터에 대한 accuracy를 
       계산하여 반환하는 cal_eval() 함수를 구현합니다.

"""
def cal_eval(test_y, pred):
    
    
    return index_3_precision, index_3_recall, accuracy

"""
    4. 구현한 함수를 활용하여 다중 클래스 분류를 진행하고,
       결과를 확인하기 위한 main() 함수를 구현합니다.
"""
def main():
    
    train_X, test_X, train_y, test_y = load_data()
    
    pred = SVM_clf(train_X, test_X, train_y)
    
    
    # 학습된 모델로 digit data가 제대로 예측 됐는 지 
    # 확인하기위한 confusion matrix를 호출합니다.
    print("Confusion matrix results :\n\t- row : real(test_y) 0 ~ 9 label\n\t- column : predicted 0 ~ 9 label\n\n%s\n"  % confusion_matrix(test_y, pred))
    
    index_3_precision, index_3_recall, accuracy = None
    
    print("index 3의 recall : %f" % index_3_recall)
    print("index 3의 precision : %f" % index_3_precision)
    print("전체 accuracy : %f" % accuracy)
    
    # 랜덤으로 뽑은 4개의 데이터를 학습된 모델로 
    # 제대로 예측 했는 지 시각화 합니다.
    draw_digit_images(test_X, test_y, pred)

if __name__ == "__main__":
    main()

Confusion matrix results :
	- row : real(test_y) 0 ~ 9 label
	- column : predicted 0 ~ 9 label

[[42  0  0  0  0  0  0  0  0  0]
 [ 0 32  0  0  0  0  0  0  0  0]
 [ 0  0 41  0  0  0  0  0  0  0]
 [ 0  0  0 32  0  0  0  0  0  0]
 [ 0  0  0  0 34  0  0  0  1  1]
 [ 0  0  0  0  0 35  0  0  0  0]
 [ 0  0  0  0  0  0 40  0  0  0]
 [ 0  0  0  0  0  0  0 39  0  0]
 [ 0  1  0  0  0  0  0  0 26  0]
 [ 0  0  0  0  0  0  0  0  0 36]]



TypeError: cannot unpack non-iterable NoneType object

In [ ]:
from elice_utils import EliceUtils
elice_utils = EliceUtils()

import matplotlib.pyplot as plt
from random import randint

## 이미지 출력을 담당하는 부분입니다.
def draw_digit_images(test_X, test_y , predicted):
    
    number = randint(0, len(test_X))
    
    images_and_labels = list(zip(test_X, test_y))
    
    for index, (image, label) in enumerate(images_and_labels[number: number + 4]):
        plt.subplot(2, 4, index + 1)
        plt.axis('off')
        image = image.reshape(8,8)
        plt.imshow(image, cmap=plt.cm.gray_r, interpolation='nearest')
        plt.title('Training: %i' % label)

    images_and_predictions = list(zip(test_X, predicted))
    #print(images_and_predictions)
    for index, (image, prediction) in enumerate(images_and_predictions[number: number + 4]):
        plt.subplot(2, 4, index + 5)
        plt.axis('off')
        image = image.reshape(8,8)
        plt.imshow(image, cmap=plt.cm.gray_r, interpolation='nearest')
        plt.title('Prediction: %i' % prediction)

    plt.savefig('digit.png')
    elice_utils.send_image('digit.png')